info:
  app:
    description: Template Spring Boot API for use of CSCI 602
    name: csci-602
    version: 1.0.0
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: openapi, swagger-ui
server:
  port: 5001
spring:
  application:
    name: csci-602
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  flyway:
    enabled: false
  mvc:
    servlet:
      load-on-startup: 1
springdoc:
  packagesToScan: edu.citadel.api
  pathsToMatch: /v1, /**
  show-actuator: true